version: "3.8"

services:
  server:
    image: rust:1.67.1
    environment:
      - RUST_LOG=warn
    working_dir: /usr/src/lark_chatgpt
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/lark_chatgpt
    command:
      - /bin/bash
      - -c
      - |
        ./target/debug/feishu_gptbot